name: Yarn CLI

on:
  push: 
    branches: 
      - main

jobs: 
  add_env_variables_at_build:
    runs-on: ubuntu-latest
    name: Add Environment Variables During Yarn Build
    steps:
      - uses: actions/checkout@v3
      - name: Run Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          env:
            ARG CLUSTER_NAME
            ARG SENTRY_UI_DSN
            ARG SENTRY_UI_RELEASE_API_TOKEN
            ARG USER_FACING_API_HTTP_PATH
            ARG CURRENT_REVISION
            ARG USER_FACING_UI_HTTP_PATH
            ARG MICROSOFT_AZURE_APP_ID
            ARG ANALYTICS_UI_SITE_ID
            ARG USE_ALTERNATE_AUTH
            ARG KIBANA_PARTIAL_URL

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
            cmd: build

  teardown_build_setup:
    runs-on: ubuntu-latest
    name: Tear Down Yarn Set-Up
    steps:
    - uses: comchangs/action-yarn@master
      with:
        args: cd exitcode-frontend; yarn install; yarn ng build
