name: Yarn CLI

on:
  push: 
    branches: 
      - main

jobs: 
  add_env_variables_at_build:
    runs-on: ubuntu-latest
    name: Add Environment Variables During Yarn Build
    steps:
    - uses: comchangs/action-yarn@e4a1f4800849aa2e73dbc77d872a3c011cdc28d5
    - uses: comchangs/action-yarn@v0.1-beta
    - name: Yarn Install
      run: yarn install
    - name: Yarn Build
      run: yarn build

  teardown_build_setup:
    runs-on: ubuntu-latest
    name: Tear Down Yarn Set-Up
    steps:
    - uses: comchangs/action-yarn@master
      with:
        args: cd exitcode-frontend; yarn install; yarn ng build
