name: Yarn CLI

on:
  push: 
    branches: 
      - main

jobs: 
  add_env_variables_at_build:
    runs-on: ubuntu-latest
    name: Add Environment Variables During Yarn Build
    steps:
    - uses: comchangs/action-yarn@e4a1f4800849aa2e73dbc77d872a3c011cdc28d5
    - uses: comchangs/action-yarn@v0.1-beta
    - name: Yarn Install
      run: yarn install
      with: 
        args:     
          -- CLUSTER_NAME
          -- SENTRY_UI_DSN
          -- SENTRY_UI_RELEASE_API_TOKEN
          -- USER_FACING_API_HTTP_PATH
          -- CURRENT_REVISION
          -- USER_FACING_UI_HTTP_PATH
          -- MICROSOFT_AZURE_APP_ID                    
          -- ANALYTICS_UI_SITE_ID
          -- USE_ALTERNATE_AUTH
          -- KIBANA_PARTIAL_URL
      
    - name: Yarn Build
      run: yarn build
