name: Yarn CLI

on:
  push: 
    branches: 
      - main

jobs: 
  add_env_variables_at_build:
    runs-on: ubuntu-latest
    name: Add Environment Variables During Yarn Build
    steps:
    - uses: CultureHQ/actions-yarn@v1.0.1
    - name: Yarn Add
      run: yarn add
          -- CLUSTER_NAME
          - -- SENTRY_UI_DSN
          - -- SENTRY_UI_RELEASE_API_TOKEN
          - -- USER_FACING_API_HTTP_PATH
          - -- CURRENT_REVISION
          - -- USER_FACING_UI_HTTP_PATH
          - -- MICROSOFT_AZURE_APP_ID
          - -- ANALYTICS_UI_SITE_ID
          - -- USE_ALTERNATE_AUTH
          - -- KIBANA_PARTIAL_URL
    - name: Yarn Build
      run: yarn build
